Avoid using <linux/ext2_fs.h> or local copies
With recent Linux kernel headers, such as since 2.9 and 3.3, the
linux/ext2_fs.h header has been removed. This causes compile failures.

  fatal error: linux/ext2_fs.h: No such file or directory
   #include <linux/ext2_fs.h>

On Debian bug tracker you can read (http://bugs.debian.org/235547#10):

  | On Mon, Mar 01, 2004 at 02:22:44AM +0100, Bernd Schubert wrote:
  | > The linux/ext2_fs.h header is needed for example for building unfs3
  | > (unfs3.sf.net) with inode generation number support.
  |
  | Don't do that.
  |
  | The exact header you need is in <ext2fs/ext2_fs.h>, from e2fslibs-dev.
  |
  | --
  | Daniel Jacobowitz
  | MontaVista Software                         Debian GNU/Linux Developer

So to compile, you will need to intall ...

  ... on Debian/Ubuntu: apt-get install e2fslibs-dev
  ... on Fedora/CentOS: yum install e2fsprogs-devel

Signed-off-by: Stephan Linz <linz@li-pro.net>